import PDFDocument from "pdfkit";

export function generateEventReceiptPdf(opts: {
  bookingId: string;
  userName: string;
  userEmail: string;
  eventTitle: string;
  city: string;
  country: string;
  startDate: string;
  endDate: string;
  seats: number;
  costPerSeat: number;
  totalAmount: number;
  paymentId: string;
}): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 50 });
    const chunks: Buffer[] = [];
    doc.on("data", (c) => chunks.push(c));
    doc.on("end",  () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const W = 595 - 100;

    /* Header bar */
    doc.rect(50, 50, W, 60).fill("#0055cc");
    doc.fillColor("#ffffff").fontSize(22).font("Helvetica-Bold")
       .text("SailX Business Tours", 70, 68, { width: W - 40 });
    doc.fontSize(10).font("Helvetica").text("Official Booking Confirmation", 70, 94);

    doc.fillColor("#1a1a1a");
    let y = 130;

    /* Title */
    doc.fontSize(16).font("Helvetica-Bold").text(opts.eventTitle, 50, y);
    y += 22;
    doc.fontSize(10).font("Helvetica").fillColor("#555")
       .text(`📍 ${opts.city}, ${opts.country}  |  📅 ${opts.startDate} – ${opts.endDate}`, 50, y);
    y += 30;

    /* Divider */
    doc.moveTo(50, y).lineTo(545, y).strokeColor("#ddd").stroke();
    y += 14;

    /* Details table */
    const rows: [string, string][] = [
      ["Booking ID",       opts.bookingId],
      ["Passenger Name",   opts.userName],
      ["Email",            opts.userEmail],
      ["Seats Booked",     String(opts.seats)],
      ["Cost per Seat",    `₹${opts.costPerSeat.toLocaleString("en-IN")}`],
      ["Total Amount",     `₹${opts.totalAmount.toLocaleString("en-IN")}`],
      ["Payment ID",       opts.paymentId],
      ["Status",           "CONFIRMED & PAID"],
    ];

    for (const [label, value] of rows) {
      doc.fontSize(9).font("Helvetica-Bold").fillColor("#555").text(label, 50, y, { width: 160 });
      doc.fontSize(10).font("Helvetica").fillColor(label === "Status" ? "#16a34a" : "#1a1a1a")
         .text(value, 215, y, { width: W - 165 });
      y += 18;
      doc.moveTo(50, y - 2).lineTo(545, y - 2).strokeColor("#f0f0f0").stroke();
    }

    y += 20;
    /* Footer note */
    doc.rect(50, y, W, 44).fill("#f0f7ff");
    doc.fontSize(9).font("Helvetica").fillColor("#0055cc")
       .text(
         "Please present this confirmation (digital or printed) on the day of the event.\nFor support: info@sailxchina.com",
         62, y + 8, { width: W - 24 }
       );

    y += 62;
    doc.fontSize(8).fillColor("#aaa").font("Helvetica")
       .text(`Generated by SailX · ${new Date().toLocaleDateString("en-IN")}`, 50, y);

    doc.end();
  });
}
